### ISSUE TITLE
website.lng Çeviri hataları

### ISSUE THREAD

**Issue by tolgaaaltas** [dlenettr/dle-turkce-yama#1]
`'rules_decline'		=>  "Kabuk etmiyorum",` yerine `'rules_decline'		=>  "Kabu etmiyorum",`
`'xfield_xno'			=>	"Hayıt",` yerine `'xfield_xno'			=>	"Hayır",`

Doğrudan düzenleme gönderilemiyor RAR içerisinde olduğu için dosyalar.

**Comment by dlenettr** [comment]
Dışarı aldım dosyaları. Pull Request ile gönderebilirsen sevinirim :)

**Comment by dlenettr** [comment]
Eklendi. Teşekkürler.
